# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class AddHostResponseData(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, host_id: str=None):
        """
        AddHostResponseData - a model defined in Swagger

        :param host_id: The host_id of this AddHostResponseData.
        :type host_id: str
        """
        self.swagger_types = {
            'host_id': str
        }

        self.attribute_map = {
            'host_id': 'host_id'
        }

        self._host_id = host_id

    @classmethod
    def from_dict(cls, dikt) -> 'AddHostResponseData':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AddHostResponse_data of this AddHostResponseData.
        :rtype: AddHostResponseData
        """
        return deserialize_model(dikt, cls)

    @property
    def host_id(self) -> str:
        """
        Gets the host_id of this AddHostResponseData.

        :return: The host_id of this AddHostResponseData.
        :rtype: str
        """
        return self._host_id

    @host_id.setter
    def host_id(self, host_id: str):
        """
        Sets the host_id of this AddHostResponseData.

        :param host_id: The host_id of this AddHostResponseData.
        :type host_id: str
        """

        self._host_id = host_id

