# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.add_object_response_data import AddObjectResponseData
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class AddObjectResponse(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, message: str=None, data: AddObjectResponseData=None):
        """
        AddObjectResponse - a model defined in Swagger

        :param message: The message of this AddObjectResponse.
        :type message: str
        :param data: The data of this AddObjectResponse.
        :type data: AddObjectResponseData
        """
        self.swagger_types = {
            'message': str,
            'data': AddObjectResponseData
        }

        self.attribute_map = {
            'message': 'message',
            'data': 'data'
        }

        self._message = message
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'AddObjectResponse':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AddObjectResponse of this AddObjectResponse.
        :rtype: AddObjectResponse
        """
        return deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """
        Gets the message of this AddObjectResponse.

        :return: The message of this AddObjectResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """
        Sets the message of this AddObjectResponse.

        :param message: The message of this AddObjectResponse.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> AddObjectResponseData:
        """
        Gets the data of this AddObjectResponse.

        :return: The data of this AddObjectResponse.
        :rtype: AddObjectResponseData
        """
        return self._data

    @data.setter
    def data(self, data: AddObjectResponseData):
        """
        Sets the data of this AddObjectResponse.

        :param data: The data of this AddObjectResponse.
        :type data: AddObjectResponseData
        """

        self._data = data

