# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.add_product_response_data import AddProductResponseData
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class AddProductResponse(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, message: str=None, data: AddProductResponseData=None):
        """
        AddProductResponse - a model defined in Swagger

        :param message: The message of this AddProductResponse.
        :type message: str
        :param data: The data of this AddProductResponse.
        :type data: AddProductResponseData
        """
        self.swagger_types = {
            'message': str,
            'data': AddProductResponseData
        }

        self.attribute_map = {
            'message': 'message',
            'data': 'data'
        }

        self._message = message
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'AddProductResponse':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AddProductResponse of this AddProductResponse.
        :rtype: AddProductResponse
        """
        return deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """
        Gets the message of this AddProductResponse.

        :return: The message of this AddProductResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """
        Sets the message of this AddProductResponse.

        :param message: The message of this AddProductResponse.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> AddProductResponseData:
        """
        Gets the data of this AddProductResponse.

        :return: The data of this AddProductResponse.
        :rtype: AddProductResponseData
        """
        return self._data

    @data.setter
    def data(self, data: AddProductResponseData):
        """
        Sets the data of this AddProductResponse.

        :param data: The data of this AddProductResponse.
        :type data: AddProductResponseData
        """

        self._data = data

