# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class AddObjectResponseData(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, object_id: str=None):
        """
        AddObjectResponseData - a model defined in Swagger

        :param object_id: The object_id of this AddObjectResponseData.
        :type object_id: str
        """
        self.swagger_types = {
            'object_id': str
        }

        self.attribute_map = {
            'object_id': 'object_id'
        }

        self._object_id = object_id

    @classmethod
    def from_dict(cls, dikt) -> 'AddObjectResponseData':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AddObjectResponse_data of this AddObjectResponseData.
        :rtype: AddObjectResponseData
        """
        return deserialize_model(dikt, cls)

    @property
    def object_id(self) -> str:
        """
        Gets the object_id of this AddObjectResponseData.

        :return: The object_id of this AddObjectResponseData.
        :rtype: str
        """
        return self._object_id

    @object_id.setter
    def object_id(self, object_id: str):
        """
        Sets the object_id of this AddObjectResponseData.

        :param object_id: The object_id of this AddObjectResponseData.
        :type object_id: str
        """

        self._object_id = object_id

