# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class AddProductResponseData(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, product_id: str=None):
        """
        AddProductResponseData - a model defined in Swagger

        :param product_id: The product_id of this AddProductResponseData.
        :type product_id: str
        """
        self.swagger_types = {
            'product_id': str
        }

        self.attribute_map = {
            'product_id': 'product_id'
        }

        self._product_id = product_id

    @classmethod
    def from_dict(cls, dikt) -> 'AddProductResponseData':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AddProductResponse_data of this AddProductResponseData.
        :rtype: AddProductResponseData
        """
        return deserialize_model(dikt, cls)

    @property
    def product_id(self) -> str:
        """
        Gets the product_id of this AddProductResponseData.

        :return: The product_id of this AddProductResponseData.
        :rtype: str
        """
        return self._product_id

    @product_id.setter
    def product_id(self, product_id: str):
        """
        Sets the product_id of this AddProductResponseData.

        :param product_id: The product_id of this AddProductResponseData.
        :type product_id: str
        """

        self._product_id = product_id

