# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class DeleteProductsResponseData(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, deleted_count: int=None):
        """
        DeleteProductsResponseData - a model defined in Swagger

        :param deleted_count: The deleted_count of this DeleteProductsResponseData.
        :type deleted_count: int
        """
        self.swagger_types = {
            'deleted_count': int
        }

        self.attribute_map = {
            'deleted_count': 'deleted_count'
        }

        self._deleted_count = deleted_count

    @classmethod
    def from_dict(cls, dikt) -> 'DeleteProductsResponseData':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DeleteProductsResponse_data of this DeleteProductsResponseData.
        :rtype: DeleteProductsResponseData
        """
        return deserialize_model(dikt, cls)

    @property
    def deleted_count(self) -> int:
        """
        Gets the deleted_count of this DeleteProductsResponseData.

        :return: The deleted_count of this DeleteProductsResponseData.
        :rtype: int
        """
        return self._deleted_count

    @deleted_count.setter
    def deleted_count(self, deleted_count: int):
        """
        Sets the deleted_count of this DeleteProductsResponseData.

        :param deleted_count: The deleted_count of this DeleteProductsResponseData.
        :type deleted_count: int
        """

        self._deleted_count = deleted_count

