# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.delete_products_response_data import DeleteProductsResponseData
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class DeleteProductsResponse(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, message: str=None, data: DeleteProductsResponseData=None):
        """
        DeleteProductsResponse - a model defined in Swagger

        :param message: The message of this DeleteProductsResponse.
        :type message: str
        :param data: The data of this DeleteProductsResponse.
        :type data: DeleteProductsResponseData
        """
        self.swagger_types = {
            'message': str,
            'data': DeleteProductsResponseData
        }

        self.attribute_map = {
            'message': 'message',
            'data': 'data'
        }

        self._message = message
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'DeleteProductsResponse':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DeleteProductsResponse of this DeleteProductsResponse.
        :rtype: DeleteProductsResponse
        """
        return deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """
        Gets the message of this DeleteProductsResponse.

        :return: The message of this DeleteProductsResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """
        Sets the message of this DeleteProductsResponse.

        :param message: The message of this DeleteProductsResponse.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> DeleteProductsResponseData:
        """
        Gets the data of this DeleteProductsResponse.

        :return: The data of this DeleteProductsResponse.
        :rtype: DeleteProductsResponseData
        """
        return self._data

    @data.setter
    def data(self, data: DeleteProductsResponseData):
        """
        Sets the data of this DeleteProductsResponse.

        :param data: The data of this DeleteProductsResponse.
        :type data: DeleteProductsResponseData
        """

        self._data = data

