# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.get_version_response_data import GetVersionResponseData
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class GetVersionResponse(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, message: str=None, data: GetVersionResponseData=None):
        """
        GetVersionResponse - a model defined in Swagger

        :param message: The message of this GetVersionResponse.
        :type message: str
        :param data: The data of this GetVersionResponse.
        :type data: GetVersionResponseData
        """
        self.swagger_types = {
            'message': str,
            'data': GetVersionResponseData
        }

        self.attribute_map = {
            'message': 'message',
            'data': 'data'
        }

        self._message = message
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'GetVersionResponse':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetVersionResponse of this GetVersionResponse.
        :rtype: GetVersionResponse
        """
        return deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """
        Gets the message of this GetVersionResponse.

        :return: The message of this GetVersionResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """
        Sets the message of this GetVersionResponse.

        :param message: The message of this GetVersionResponse.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> GetVersionResponseData:
        """
        Gets the data of this GetVersionResponse.

        :return: The data of this GetVersionResponse.
        :rtype: GetVersionResponseData
        """
        return self._data

    @data.setter
    def data(self, data: GetVersionResponseData):
        """
        Sets the data of this GetVersionResponse.

        :param data: The data of this GetVersionResponse.
        :type data: GetVersionResponseData
        """

        self._data = data

