# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class GetVersionResponseData(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, version_name: str=None):
        """
        GetVersionResponseData - a model defined in Swagger

        :param version_name: The version_name of this GetVersionResponseData.
        :type version_name: str
        """
        self.swagger_types = {
            'version_name': str
        }

        self.attribute_map = {
            'version_name': 'version_name'
        }

        self._version_name = version_name

    @classmethod
    def from_dict(cls, dikt) -> 'GetVersionResponseData':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetVersionResponse_data of this GetVersionResponseData.
        :rtype: GetVersionResponseData
        """
        return deserialize_model(dikt, cls)

    @property
    def version_name(self) -> str:
        """
        Gets the version_name of this GetVersionResponseData.

        :return: The version_name of this GetVersionResponseData.
        :rtype: str
        """
        return self._version_name

    @version_name.setter
    def version_name(self, version_name: str):
        """
        Sets the version_name of this GetVersionResponseData.

        :param version_name: The version_name of this GetVersionResponseData.
        :type version_name: str
        """

        self._version_name = version_name

