# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class GetVersionResponseData(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id: str=None, version_name: str=None, created_at: str=None):
        """
        GetVersionResponseData - a model defined in Swagger

        :param id: The id of this GetVersionResponseData.
        :type id: str
        :param version_name: The version_name of this GetVersionResponseData.
        :type version_name: str
        :param created_at: The created_at of this GetVersionResponseData.
        :type created_at: str
        """
        self.swagger_types = {
            'id': str,
            'version_name': str,
            'created_at': str
        }

        self.attribute_map = {
            'id': 'id',
            'version_name': 'version_name',
            'created_at': 'created_at'
        }

        self._id = id
        self._version_name = version_name
        self._created_at = created_at

    @classmethod
    def from_dict(cls, dikt) -> 'GetVersionResponseData':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetVersionResponse_data of this GetVersionResponseData.
        :rtype: GetVersionResponseData
        """
        return deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """
        Gets the id of this GetVersionResponseData.

        :return: The id of this GetVersionResponseData.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """
        Sets the id of this GetVersionResponseData.

        :param id: The id of this GetVersionResponseData.
        :type id: str
        """

        self._id = id

    @property
    def version_name(self) -> str:
        """
        Gets the version_name of this GetVersionResponseData.

        :return: The version_name of this GetVersionResponseData.
        :rtype: str
        """
        return self._version_name

    @version_name.setter
    def version_name(self, version_name: str):
        """
        Sets the version_name of this GetVersionResponseData.

        :param version_name: The version_name of this GetVersionResponseData.
        :type version_name: str
        """

        self._version_name = version_name

    @property
    def created_at(self) -> str:
        """
        Gets the created_at of this GetVersionResponseData.

        :return: The created_at of this GetVersionResponseData.
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: str):
        """
        Sets the created_at of this GetVersionResponseData.

        :param created_at: The created_at of this GetVersionResponseData.
        :type created_at: str
        """

        self._created_at = created_at

