# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.host import Host
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class GetHostsResponse(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, message: str=None, data: List[Host]=None):
        """
        GetHostsResponse - a model defined in Swagger

        :param message: The message of this GetHostsResponse.
        :type message: str
        :param data: The data of this GetHostsResponse.
        :type data: List[Host]
        """
        self.swagger_types = {
            'message': str,
            'data': List[Host]
        }

        self.attribute_map = {
            'message': 'message',
            'data': 'data'
        }

        self._message = message
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'GetHostsResponse':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetHostsResponse of this GetHostsResponse.
        :rtype: GetHostsResponse
        """
        return deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """
        Gets the message of this GetHostsResponse.

        :return: The message of this GetHostsResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """
        Sets the message of this GetHostsResponse.

        :param message: The message of this GetHostsResponse.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> List[Host]:
        """
        Gets the data of this GetHostsResponse.

        :return: The data of this GetHostsResponse.
        :rtype: List[Host]
        """
        return self._data

    @data.setter
    def data(self, data: List[Host]):
        """
        Sets the data of this GetHostsResponse.

        :param data: The data of this GetHostsResponse.
        :type data: List[Host]
        """

        self._data = data

