# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class SubImage(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, origin: str=None, mobile: str=None, main: int=None):
        """
        SubImage - a model defined in Swagger

        :param origin: The origin of this SubImage.
        :type origin: str
        :param mobile: The mobile of this SubImage.
        :type mobile: str
        :param main: The main of this SubImage.
        :type main: int
        """
        self.swagger_types = {
            'origin': str,
            'mobile': str,
            'main': int
        }

        self.attribute_map = {
            'origin': 'origin',
            'mobile': 'mobile',
            'main': 'main'
        }

        self._origin = origin
        self._mobile = mobile
        self._main = main

    @classmethod
    def from_dict(cls, dikt) -> 'SubImage':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SubImage of this SubImage.
        :rtype: SubImage
        """
        return deserialize_model(dikt, cls)

    @property
    def origin(self) -> str:
        """
        Gets the origin of this SubImage.

        :return: The origin of this SubImage.
        :rtype: str
        """
        return self._origin

    @origin.setter
    def origin(self, origin: str):
        """
        Sets the origin of this SubImage.

        :param origin: The origin of this SubImage.
        :type origin: str
        """

        self._origin = origin

    @property
    def mobile(self) -> str:
        """
        Gets the mobile of this SubImage.

        :return: The mobile of this SubImage.
        :rtype: str
        """
        return self._mobile

    @mobile.setter
    def mobile(self, mobile: str):
        """
        Sets the mobile of this SubImage.

        :param mobile: The mobile of this SubImage.
        :type mobile: str
        """

        self._mobile = mobile

    @property
    def main(self) -> int:
        """
        Gets the main of this SubImage.
        1: main, 0: sub image

        :return: The main of this SubImage.
        :rtype: int
        """
        return self._main

    @main.setter
    def main(self, main: int):
        """
        Sets the main of this SubImage.
        1: main, 0: sub image

        :param main: The main of this SubImage.
        :type main: int
        """

        self._main = main

