# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class UpdateProductResponse(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, product_id: str=None, modified_count: int=None, created_count: int=None, message: str=None):
        """
        UpdateProductResponse - a model defined in Swagger

        :param product_id: The product_id of this UpdateProductResponse.
        :type product_id: str
        :param modified_count: The modified_count of this UpdateProductResponse.
        :type modified_count: int
        :param created_count: The created_count of this UpdateProductResponse.
        :type created_count: int
        :param message: The message of this UpdateProductResponse.
        :type message: str
        """
        self.swagger_types = {
            'product_id': str,
            'modified_count': int,
            'created_count': int,
            'message': str
        }

        self.attribute_map = {
            'product_id': 'product_id',
            'modified_count': 'modified_count',
            'created_count': 'created_count',
            'message': 'message'
        }

        self._product_id = product_id
        self._modified_count = modified_count
        self._created_count = created_count
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateProductResponse':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdateProductResponse of this UpdateProductResponse.
        :rtype: UpdateProductResponse
        """
        return deserialize_model(dikt, cls)

    @property
    def product_id(self) -> str:
        """
        Gets the product_id of this UpdateProductResponse.

        :return: The product_id of this UpdateProductResponse.
        :rtype: str
        """
        return self._product_id

    @product_id.setter
    def product_id(self, product_id: str):
        """
        Sets the product_id of this UpdateProductResponse.

        :param product_id: The product_id of this UpdateProductResponse.
        :type product_id: str
        """

        self._product_id = product_id

    @property
    def modified_count(self) -> int:
        """
        Gets the modified_count of this UpdateProductResponse.

        :return: The modified_count of this UpdateProductResponse.
        :rtype: int
        """
        return self._modified_count

    @modified_count.setter
    def modified_count(self, modified_count: int):
        """
        Sets the modified_count of this UpdateProductResponse.

        :param modified_count: The modified_count of this UpdateProductResponse.
        :type modified_count: int
        """

        self._modified_count = modified_count

    @property
    def created_count(self) -> int:
        """
        Gets the created_count of this UpdateProductResponse.

        :return: The created_count of this UpdateProductResponse.
        :rtype: int
        """
        return self._created_count

    @created_count.setter
    def created_count(self, created_count: int):
        """
        Sets the created_count of this UpdateProductResponse.

        :param created_count: The created_count of this UpdateProductResponse.
        :type created_count: int
        """

        self._created_count = created_count

    @property
    def message(self) -> str:
        """
        Gets the message of this UpdateProductResponse.

        :return: The message of this UpdateProductResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """
        Sets the message of this UpdateProductResponse.

        :param message: The message of this UpdateProductResponse.
        :type message: str
        """

        self._message = message

