# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Version(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id: str=None, created_at: datetime=None, name: str=None):
        """
        Version - a model defined in Swagger

        :param id: The id of this Version.
        :type id: str
        :param created_at: The created_at of this Version.
        :type created_at: datetime
        :param name: The name of this Version.
        :type name: str
        """
        self.swagger_types = {
            'id': str,
            'created_at': datetime,
            'name': str
        }

        self.attribute_map = {
            'id': 'id',
            'created_at': 'created_at',
            'name': 'name'
        }

        self._id = id
        self._created_at = created_at
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'Version':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Version of this Version.
        :rtype: Version
        """
        return deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """
        Gets the id of this Version.

        :return: The id of this Version.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """
        Sets the id of this Version.

        :param id: The id of this Version.
        :type id: str
        """

        self._id = id

    @property
    def created_at(self) -> datetime:
        """
        Gets the created_at of this Version.

        :return: The created_at of this Version.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: datetime):
        """
        Sets the created_at of this Version.

        :param created_at: The created_at of this Version.
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def name(self) -> str:
        """
        Gets the name of this Version.

        :return: The name of this Version.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """
        Sets the name of this Version.

        :param name: The name of this Version.
        :type name: str
        """

        self._name = name

